name: Preview
on:
    workflow_call: 
        inputs:
            stack-name:
                description: "Stack Pulumi name"
                required: false
                default: ${{ github.base_ref }}
                type: string

jobs:
    preview:
        name: Preview
        runs-on: ubuntu-latest #[self-hosted] #[pulumi, azure]
        environment: ${{ inputs.stack-name }}
        steps:
            - id: extract_service_principal
              name: Extract service principal
              uses: azure-deploy/extract-sp-subscription-id@main
              with:
                stack-name: ${{ inputs.stack-name }}
            - id: extract_subscription_id
              name: Extract subscription ID
              uses: azure-deploy/extract-sp-subscription-id@main
              with:
                stack-name: ${{ inputs.stack-name }}
            - id: Pulumi-preview
              name: pulumi preview
              uses: azure-deploy/preview
              with:
                stack-name: ${{ inputs.stack-name }}
                pulumi-acces-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
                az-client-id: ${{ secrets.AZ_CLIENT_ID }}
                az-client-secret: ${{ secrets.AZ_CLIENT_SECRETS }}
                az-tenant-id: ${{ secrets.AZ_TENANT_ID }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
                
