name: 'Destroy'
on:
    workflow_call: 
        inputs:
            stack-name: 
                description: "Pulimi stack name"
                required: false
                default: ${{github.base_ref}}
                type: string
jobs:
    destroy:
        name: Destroy
        runs-on: [self-hosted] #ubuntu-latest #[pulumi, azure]
        environment: ${{inputs.stack-name}}
        steps:
            - id: extract_service_principal
              name: Extract service principal
              uses: serignemodou/pulumi-azure-params@latest
              with:
                stack-name: ${{ inputs.stack-name }}
            - id: extract_subscription_id
              name: Extract subscription ID
              uses: serignemodou/pulumi-azure-params@latest
              with:
                stack-name: ${{ inputs.stack-name }}
            - id: Pulumi-Destroy
              name: pulumi destroy
              uses: serignemodou/PulumiDestroy@latest
              with:
                pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
                az-client-id: ${{ secrets[format('{0}_CLIENT_ID', steps.extract_service_principal.outputs.service-principal)] }}
                az-client-secret: ${{ secrets[format('{0}_CLIENT_SECRET', steps.extract_service_principal.outputs.ervice-principal)] }}
